{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.rallista",
    "module": "valhalla-mobile",
    "version": "0.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "valhalla-mobile-0.6.1.aar",
          "url": "valhalla-mobile-0.6.1.aar",
          "size": 16304083,
          "sha512": "19094cf788613844aca9ca4b3144e1c7e98572dc821949526654bdf01ff50489079868111e190a40032212692207732557ab221be8643cfb8d034489c9410f30",
          "sha256": "c3b101dc820816829e30582c3b241c67f77ca557c46d1192686b4672dd6ca526",
          "sha1": "87a3f8e6211056a171d468fb237e685c966ed687",
          "md5": "4e894ca9bf3f4687b252008d0b1c53d4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.15.1"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-adapters",
          "version": {
            "requires": "1.15.1"
          }
        },
        {
          "group": "io.github.rallista",
          "module": "valhalla-models",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "io.github.rallista",
          "module": "valhalla-models-config",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.stadiamaps",
          "module": "osrm-openapi",
          "version": {
            "requires": "0.0.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "valhalla-mobile-0.6.1.aar",
          "url": "valhalla-mobile-0.6.1.aar",
          "size": 16304083,
          "sha512": "19094cf788613844aca9ca4b3144e1c7e98572dc821949526654bdf01ff50489079868111e190a40032212692207732557ab221be8643cfb8d034489c9410f30",
          "sha256": "c3b101dc820816829e30582c3b241c67f77ca557c46d1192686b4672dd6ca526",
          "sha1": "87a3f8e6211056a171d468fb237e685c966ed687",
          "md5": "4e894ca9bf3f4687b252008d0b1c53d4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "valhalla-mobile-0.6.1-sources.jar",
          "url": "valhalla-mobile-0.6.1-sources.jar",
          "size": 7356,
          "sha512": "76e7cfe824b89ae2a5c672e4805ae817ec9dc2a8b1168b8b349c079cbb6e682f71990494b03aa2b62870e73ab9ea0cf3bfaae385d03bf8f51942319b49fde131",
          "sha256": "1ddd578b5c0fccb3773b45bdfb0aa0b17ec05e0246ace2b30d0e73b4d73b91b5",
          "sha1": "06c4a94c1b04f622eb5234235d6efe0c33d6c4ef",
          "md5": "a4e09745a7591b45cf3f13d122a119f3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "valhalla-mobile-0.6.1-javadoc.jar",
          "url": "valhalla-mobile-0.6.1-javadoc.jar",
          "size": 332289,
          "sha512": "003c9af27e0835653847da7a3e8cb56444605cf55767c342b39bd2cad18e392613201c189764640875bf529c27251332179a7fb43e14890f45c87e666dce4c8b",
          "sha256": "7d622b109f8166a1b79c88edd73dad631801e7e136afaecdb867c3075f0bdaeb",
          "sha1": "36e4b0915dc7893bf54682712894d8bba7763e17",
          "md5": "6eb8fdd53488ba66302d46d4e8543f51"
        }
      ]
    }
  ]
}
