{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.activetripme",
    "module": "valhalla-mobile",
    "version": "0.6.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "valhalla-mobile-0.6.3.aar",
          "url": "valhalla-mobile-0.6.3.aar",
          "size": 16304083,
          "sha512": "09e040c9ae0d892053d9c7007c3207854e8a363bb88125328750f5eca5625305ab03b56df916d8352abe3475f4ac1317f5cbb0a2d2cba4a60ee5b1fedf20fe91",
          "sha256": "cffb698fc4feb19b7cb14a0d90ec96ded8a2e87f0a02433e346c010158f77140",
          "sha1": "a3a7bfeeff3f5025bd9efd92cab31cc2cecc8308",
          "md5": "fc9437efc10d4999bccb4b1993d57cd4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.15.1"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-adapters",
          "version": {
            "requires": "1.15.1"
          }
        },
        {
          "group": "io.github.rallista",
          "module": "valhalla-models",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "io.github.rallista",
          "module": "valhalla-models-config",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.stadiamaps",
          "module": "osrm-openapi",
          "version": {
            "requires": "0.0.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "valhalla-mobile-0.6.3.aar",
          "url": "valhalla-mobile-0.6.3.aar",
          "size": 16304083,
          "sha512": "09e040c9ae0d892053d9c7007c3207854e8a363bb88125328750f5eca5625305ab03b56df916d8352abe3475f4ac1317f5cbb0a2d2cba4a60ee5b1fedf20fe91",
          "sha256": "cffb698fc4feb19b7cb14a0d90ec96ded8a2e87f0a02433e346c010158f77140",
          "sha1": "a3a7bfeeff3f5025bd9efd92cab31cc2cecc8308",
          "md5": "fc9437efc10d4999bccb4b1993d57cd4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "valhalla-mobile-0.6.3-sources.jar",
          "url": "valhalla-mobile-0.6.3-sources.jar",
          "size": 7356,
          "sha512": "76e7cfe824b89ae2a5c672e4805ae817ec9dc2a8b1168b8b349c079cbb6e682f71990494b03aa2b62870e73ab9ea0cf3bfaae385d03bf8f51942319b49fde131",
          "sha256": "1ddd578b5c0fccb3773b45bdfb0aa0b17ec05e0246ace2b30d0e73b4d73b91b5",
          "sha1": "06c4a94c1b04f622eb5234235d6efe0c33d6c4ef",
          "md5": "a4e09745a7591b45cf3f13d122a119f3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "valhalla-mobile-0.6.3-javadoc.jar",
          "url": "valhalla-mobile-0.6.3-javadoc.jar",
          "size": 332291,
          "sha512": "13aec0aaf71241b20fe3b4d26be2d54852429417f6517746766975ffb1777f6e7e7ff4b6550bf9fa5ced77a165ea8a89606b55e985dc5e38156b07f9cb4379f3",
          "sha256": "a7385893e152bd2af093d75f1d81d8da3f19f27a10a9acabfbd17f525a10d710",
          "sha1": "35253cbd6ce38919bc1a80bf2b87927ba5dba0da",
          "md5": "77f2c92c611c6a93fa99045f12a5b19f"
        }
      ]
    }
  ]
}
